---

# Configuration options
conf_file: '{{ test_conf_file | realpath }}'

default_conf:
  DEFAULT:
    debug: "{{ log_debug }}"
    log_dir: "{{ log_file | dirname }}"
    log_file: "{{ log_file | basename }}"

conf: {}

# Logging options
log_debug: '{{ test_log_debug | bool }}'
log_file: "{{ test_log_file | realpath }}"

# OpenStack client credentials
stackrc_file: '{{ user_home }}/overcloudrc'
