---

- name: "show ansible distro variables"
  debug:
    msg:
      ansible_architecture: '{{ ansible_architecture }}'
      ansible_distribution: '{{ ansible_distribution }}'
      ansible_distribution_major_version: '{{ ansible_distribution_major_version }}'
      ansible_os_family: '{{ ansible_os_family }}'


- name: "include OS-specific variables"
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yaml"
    - "{{ ansible_distribution }}.{{ ansible_architecture }}.yaml"
    - "{{ ansible_distribution }}.yaml"
    - "{{ ansible_os_family }}.yaml"


- block:
    - name: "ensures '{{ python3_executable }}' command is available"
      include_tasks: python3.yaml
      when:
        - python3_info is not defined

    - name: "ensures '{{ python_executable }}' command is available"
      include_tasks: python.yaml
      when:
        - python_info is not defined
