---

- name: "show ansible distro variables"
  debug:
    msg:
      ansible_architecture: '{{ ansible_architecture }}'
      ansible_distribution: '{{ ansible_distribution }}'
      ansible_distribution_major_version: '{{ ansible_distribution_major_version }}'
      ansible_os_family: '{{ ansible_os_family }}'


- name: "include platform variables"
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yaml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yaml"
    - "{{ ansible_distribution }}.{{ ansible_architecture }}.yaml"
    - "{{ ansible_distribution }}.yaml"
    - "{{ ansible_os_family }}.yaml"
  register: include_platform_vars


- name: "set Python platform facts"
  set_fact:
    python_platform:
      '{{ (include_platform_vars.results | first).item | basename | splitext | first }}'


- name: 'show Python platform facts'
  debug:
    msg: '{{ (include_platform_vars.results | first).ansible_facts }}'
