---

tobiko_src_dir: "{{ zuul.executor.work_root }}/{{ zuul.projects['opendev.org/x/tobiko'].src_dir }}"
# tobiko_dir: '/opt/stack/tobiko'
tobiko_user: 'zuul'
# test_conf_file: '/etc/tobiko/tobiko.conf'
test_src_dir: '{{ zuul.executor.work_root }}/{{ zuul.project.src_dir }}'
test_dir: '{{ tobiko_dir }}'
test_user: 'zuul'
test_collect_dir: '{{ zuul.executor.log_root }}'
