---

- hosts: all
  roles:

    - role: .
      vars:
        python_version: "3.8"
        python_release: "3.8.0"
        pip_install_packages:
          - virtualenv
          - tox

  tasks:

    - name: run test cases
      shell:
        cmd: tox -e py38
        chdir: /vagrant
      register: run_test_cases
      ignore_errors: true

    - name: Install Python devel package required to compile tox reports
      yum:
        name: python-devel
        state: latest

    - name: produce test reports
      shell:
        cmd: tox -e report 2>&1
        chdir: /vagrant

    - name: get test reports
      fetch:
        src: "/vagrant/{{ item }}"
        dest: "{{ playbook_dir }}/tox-py38/{{ inventory_hostname }}/{{ item }}"
        flat: yes
      loop:
        - tobiko_results.html

    - name: check test cases result
      assert:
        that: run_test_cases.rc == 0
        fail_msg: |
          Test cases failed
          {{ run_test_cases.stdout }}
        success_msg: |
          Test cases passed
          {{ run_test_cases.stdout }}
