---

- become: yes
  become_user: root
  block:

    - name: "provide {{ tobiko_conf_file }} file"
      ini_file:
        path: "{{ tobiko_conf_file }}"
        section: '{{ item.section }}'
        option: '{{ item.option }}'
        value: '{{ item.value }}'
        owner: root
        mode: '0644'
      loop: "{{ tobiko_conf_options }}"
      when: item.value

    - name: "read {{ tobiko_conf_file }} file"
      slurp:
        src: "{{ tobiko_conf_file }}"
      register: read_tobiko_conf_file

    - name: "show {{ tobiko_conf_file }} file"
      debug:
        msg: "{{ read_tobiko_conf_file['content'] | b64decode }}"
