---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: requirements-txt-fixer
        args: [requirements.txt, test-requirements.txt, extra-requirements.txt, linters-requirements.txt, doc/requirements.txt, infrared_plugin/requirements.txt]
      - id: trailing-whitespace

#  - repo: https://github.com/adrienverge/yamllint.git
#    rev: v1.23.0
#    hooks:
#      - id: yamllint
#        files: \.(yaml|yml)$

#  - repo: https://opendev.org/openstack/bashate.git
#    rev: 2.0.0
#    hooks:
#      - id: bashate
