---

version: '3.4'
services:
  unit:
    build:
      context: .
      target: tobiko
    hostname: tobiko
    environment:
      OS_TEST_PATH: tobiko/tests/unit
      TOX_REPORT_NAME: tobiko_results_unit
    volumes:
      - ./report:/report

  shell:
    extends:
      service: unit
    entrypoint: /bin/bash

  functional:
    extends:
      service: unit
    environment:
      OS_TEST_PATH: tobiko/tests/functional
      TOX_REPORT_NAME: tobiko_results_functional

  create:
    extends:
      service: unit
    environment:
      OS_TEST_PATH: tobiko/tests/scenario
      TOX_REPORT_NAME: tobiko_results_create

  disrupt:
    extends:
      service: unit
    environment:
      OS_TEST_PATH: tobiko/tests/faults
      TOX_REPORT_NAME: tobiko_results_disrupt

  verify:
    extends:
      service: create
    environment:
      PREVENT_CREATE: 'true'
      TOX_REPORT_NAME: tobiko_results_verify
