---

version: '3.4'
services:
  py3:
    build:
      context: .
      target: test
    hostname: tobiko
    environment:
      OS_TEST_PATH: tobiko/tests/unit
      TOX_REPORT_NAME: tobiko_results_py3
    volumes:
      - ./report:/report
      - .:/tobiko
      - ~/.ssh:/root/.ssh

  lower-constraints:
    extends:
      service: py3
    build:
      args:
        base_image: lower-constraints
    environment:
      TOX_REPORT_NAME: tobiko_results_lower_constraints

  py39:
    extends:
      service: py3
    build:
      args:
        base_image: py39
    environment:
      TOX_REPORT_NAME: tobiko_results_py39

  py310:
    extends:
      service: py3
    build:
      args:
        base_image: py310
    environment:
      TOX_REPORT_NAME: tobiko_results_py310

  linters:
    extends:
      service: py3
    build:
      target: linters

  functional:
    extends:
      service: py3
    environment:
      OS_TEST_PATH: tobiko/tests/functional
      TOX_REPORT_NAME: tobiko_results_functional

  create-workloads:
    extends:
      service: py3
    environment:
      OS_TEST_PATH: tobiko/tests/scenario
      TOX_REPORT_NAME: tobiko_results_create_workloads

  disrupt-services:
    extends:
      service: py3
    environment:
      OS_TEST_PATH: tobiko/tests/faults
      TOX_REPORT_NAME: tobiko_results_disrupt_services

  verify-workloads:
    extends:
      service: create-workloads
    environment:
      PREVENT_CREATE: 'true'
      TOX_REPORT_NAME: tobiko_results_verify_workloads

  verify-services:
    extends:
      service: py3
    environment:
      OS_TEST_PATH: tobiko/tests/sanity
      TOX_REPORT_NAME: tobiko_results_verify_services

  infrared:
    build:
      context: infrared_plugin
      target: tobiko-infrared
    hostname: tobiko-infrared
    environment:
      IR_EXTRA_ARGS: --tobiko-src-dir /tobiko
    volumes:
      - ./report:/report
      - .:/tobiko
      - ./infrared_plugin:/tobiko-infrared
      - ~/.ssh:/root/.ssh
