---

- hosts: '{{ test_host }}'
  gather_facts: yes
  any_errors_fatal: yes
  roles:

    - role: tobiko-common

    - role: tobiko-deploy
      vars:
        src_dir: '{{ tobiko_src_dir }}'
        dest_dir: '{{ tobiko_dir }}'
        git_repo: '{{ tobiko_git_repo }}'
        git_refspec: '{{ tobiko_git_refspec }}'
        git_version: '{{ tobiko_git_version }}'
      when:
        - test_stage in ['all', 'pre-run', 'deploy', 'deploy-tobiko']

    - role: tobiko-deploy
      vars:
        src_dir: '{{ test_src_dir }}'
        dest_dir: '{{ test_dir }}'
        git_repo: '{{ test_git_repo }}'
        git_refspec: '{{ test_git_refspec }}'
        git_version: '{{ test_git_version }}'
      when:
        - test_stage in ['all', 'pre-run', 'deploy', 'deploy-test']
        - tobiko_dir != test_dir

    - role: tobiko-configure
      when:
        - test_stage in ['all', 'pre-run', 'configure']

    - role: tobiko-tox
      ignore_errors: yes
      when:
        - test_stage in ['all', 'run', 'tox']

    - role: tobiko-collect
      when:
        - test_stage in ['all', 'post-run', 'collect']


- hosts: '{{ test_host }}'
  tasks:

    - name: 'report test failure'
      debug:
        msg: 'Test cases have failed'
      failed_when: yes
      when:
        - run_tox is defined
        - run_tox is failed
