---

- hosts: all
  tasks:
    - name: "ensure test results directory is writable by user '{{ ansible_user }}'"
      file:
        path: '{{ item }}'
        state: directory
        owner: '{{ ansible_user }}'
        mode: '0755'
      become: yes
      loop:
        - '{{ test_results_dir }}'
