---

- hosts: all
  vars:
    zuul_output_dir: '{{ ansible_user_dir }}/zuul-output'
    test_collect_dir: '{{ zuul_output_dir }}/logs'

  roles:
    - role: tobiko-ensure-python

    - name: "run Tox InfraRed plugin"
      role: tox
      vars:
        tox_envlist: infrared
        tox_extra_args:
          '-- --collect-dir {{ test_collect_dir | quote }}'
        tox_environment:
          PYTHON: '{{ unversioned_python_executable }}'
          ANSIBLE_PYTHON_INTERPRETER: '{{ unversioned_python_executable }}'

  tasks:
    - name: "list collected files"
      command: >
        ls '{{ test_collect_dir }}'
      register: list_test_result_files

    - name: "set collected files fact"
      set_fact:
        collected_files: '{{ list_test_result_files.stdout_lines }}'

    - name: "show collected files"
      debug: var=collected_files

    - name: "check collected files"
      assert:
        that:
          - item in collected_files
      loop:
        - tobiko.log
        - tobiko.conf
        - test_results.html
        - test_results.subunit
        - test_results.xml
