---
- name: "cleanup Loadbalancers created by Tobiko tests"
  shell: |
    source {{ stackrc_file }}
    openstack loadbalancer list -f value -c 'name' | \
        grep "^tobiko\." | \
        xargs -r openstack loadbalancer delete --cascade --wait
  ignore_errors: yes

- name: "cleanup Heat stacks created by Tobiko tests"
  shell: |
    source {{ stackrc_file }}
    openstack stack list -f value -c 'Stack Name' | \
        grep "^tobiko\." | \
        xargs -r openstack stack delete -y --wait
  ignore_errors: yes

- name: "cleanup Glance images created by Tobiko tests"
  shell: |
    source {{ stackrc_file }}
    openstack image list -f value -c 'Name' | \
        grep "^tobiko\." | \
        xargs -r openstack image delete
  ignore_errors: yes
