---

- name: check '{{ pip_command }}' command
  command: "'{{ pip_command }}' --version"
  changed_when: false


- name: discover '{{ pip_command }}' executable path
  command: "which '{{ pip_command }}'"
  register: discover_pip_executable
  changed_when: false


- name: register '{{ pip_command }}' executable as '{{ discover_pip_executable.stdout }}'
  set_fact:
    pip_executable: '{{ discover_pip_executable.stdout }}'
