---

- name: discover sudo secure_path
  command: |
    awk '($1 == "Defaults" && $2 == "secure_path"){print $NF}' /etc/sudoers
  register: discover_sudo_secure_path


- name: add '{{ python_executable | dirname }}' to sudo 'secure_path'
  lineinfile:
    regex: '{{ discover_sudo_secure_path.stdout }}$'
    path: /etc/sudoers
    line:
      'Defaults    secure_path = {{ python_executable | dirname }}:{{ discover_sudo_secure_path.stdout }}'
    validate: '/usr/sbin/visudo -cf %s'
  when:
    - (python_executable | dirname) not in discover_sudo_secure_path.stdout
