---

- name: "expand actual user home directory"
  command: 'echo "{{ user_home }}"'
  register: expand_user_home


- name: "update user home directory"
  set_fact:
    user_home: '{{ expand_user_home.stdout.strip() | realpath }}'


- name: "show actual user home directory"
  debug: var=user_home
