---

- name: "generate local SSH key '{{ ssh_key_file }}'"
  openssh_keypair:
    path: '{{ ssh_key_file }}'
    type: ecdsa
    size: 521
    state: present
    force: no
  delegate_to: localhost


- name: "copy '{{ ssh_key_file }}' file to host"
  copy:
    src: '{{ ssh_key_file }}{{ item }}'
    dest: '/home/vagrant/.ssh/id_ecdsa{{ item }}'
    owner: vagrant
    group: vagrant
    mode: '0600'
  loop:
    - ''
    - '.pub'
