---

# Directory where files has to be deployed to
src_dir: '{{ tobiko_src_dir }}'
dest_dir: '{{ tobiko_dir }}'

git_repo: '{{ tobiko_git_repo }}'
git_refspec: '{{ tobiko_git_refspec }}'
git_version: '{{ tobiko_git_version }}'

clean_deploy_dir: false
