- project:
    templates:
      - ansible-role-jobs
      - build-openstack-docs-pti
      - docs-on-readthedocs
      - openstack-cover-jobs
      - openstack-python3-train-jobs
      - openstack-python3-ussuri-jobs
      - publish-to-pypi
      - build-release-notes-jobs-python3
    vars:
        rtd_webhook_id: '84947'

    check:
      jobs:
        - tobiko-tox-py36-centos-8
        - tobiko-tox-py38-centos-8
        - tobiko-devstack-functional-ubuntu-bionic
        - tobiko-devstack-functional-centos-7
        - tobiko-devstack-faults-centos-7
        - tobiko-devstack-faults-ubuntu-bionic
        - tobiko-tox-infrared-centos-7
        - tobiko-tox-infrared-centos-8
        - tobiko-tox-infrared-ubuntu-bionic
        - tobiko-tripleo-functional
        - tobiko-tripleo-faults

    gate:
      jobs:
        - tobiko-devstack-functional
        - tobiko-tox-infrared-centos-8
