- project:
    templates:
      - ansible-role-jobs
      - build-openstack-docs-pti
      - docs-on-readthedocs
      - openstack-cover-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - openstack-python37-jobs
      - openstack-python-jobs
      - publish-to-pypi
      - build-release-notes-jobs-python3
    vars:
        rtd_webhook_id: '84947'

    check:
      jobs:
        - tobiko-tox-py38
        - tobiko-devstack-functional
        - tobiko-devstack-scenario
        - tobiko-devstack-faults-centos-7
        - tobiko-devstack-faults-centos-7-queens
        - tobiko-devstack-faults-centos-7-train
        - tobiko-devstack-faults-ubuntu-bionic

    gate:
      jobs:
        - tobiko-tox-py38

    experimental:
      jobs:
        - tobiko-devstack-ovn-functional
        - tobiko-devstack-ovn-faults-centos-7
        - tobiko-devstack-ovn-faults-centos-7-queens
        - tobiko-devstack-ovn-faults-ubuntu-bionic
