- project:
    templates:
      - ansible-role-jobs
      - build-openstack-docs-pti
      - build-release-notes-jobs-python3
      - check-requirements
      - docs-on-readthedocs
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-wallaby-jobs
      - publish-to-pypi
      - devstack-tobiko-gate
    vars:
        rtd_webhook_id: '84947'

    check:
      jobs:
        - devstack-tobiko-faults-ubuntu
        - tobiko-tox-infrared-centos-7
        - tobiko-tox-infrared-centos-8
        - tobiko-tox-infrared-fedora-latest
        - tobiko-tox-infrared-ubuntu-focal

    gate:
      jobs:
        - tobiko-tox-infrared-centos-8

    periodic:
      jobs:
        - tripleo-ci-centos-8-content-provider
        - tobiko-tripleo-functional:
            vars: &consumer_vars
              consumer_job: true
              build_container_images: false
              remove_tags:
                - build
            dependencies: &deps_cprovider
              - tripleo-ci-centos-8-content-provider
        - tobiko-tripleo-faults:
            vars: *consumer_vars
            dependencies: *deps_cprovider
