- project:
    templates:
      - ansible-role-jobs
      - build-openstack-docs-pti
      - docs-on-readthedocs
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-train-jobs
      - openstack-python3-ussuri-jobs
      - publish-to-pypi
      - build-release-notes-jobs-python3
    vars:
        rtd_webhook_id: '84947'

    check:
      jobs:
        - tobiko-devstack-functional-centos-8
        - tobiko-devstack-functional-ubuntu-focal
        - tobiko-devstack-faults-centos-8
        - tobiko-devstack-faults-ubuntu-focal
        - tobiko-tox-infrared-centos-7
        - tobiko-tox-infrared-centos-8
        - tobiko-tox-infrared-fedora-latest
        - tobiko-tox-infrared-ubuntu-focal

    gate:
      jobs:
        - tobiko-devstack-functional-centos-8
        - tobiko-tox-infrared-centos-8

    periodic:
      jobs:
        - tobiko-devstack-functional-centos-8
        - tobiko-devstack-functional-ubuntu-focal
        - tobiko-devstack-faults-centos-8
        - tobiko-devstack-faults-ubuntu-focal
        - tobiko-tripleo-functional
        - tobiko-tripleo-faults
