---

# --- Tobiko workflow stages

test_stage: all


# --- Test deploy options -----------------------------------------------------

test_deploy_home: '{{ ansible_user_dir | realpath }}/src'

git_base: 'https://opendev.org'

test_dir: "{{ test_deploy_home }}/{{ test_project }}"
test_project:
  "{{ test_git_repo | urlsplit('path') | regex_replace('^\\/|\\/$', '') | splitext | first }}"
test_git_repo: '{{ git_base }}/x/tobiko.git'
test_git_refspec: ''
test_git_remote: 'origin'
test_git_version: 'master'
test_src_dir: ''


# NOTE: if test_dir and tobiko_dir variables endup being the same actual
# directory then test_src and test_git_* variables will be overriden
# tobiko_src and tobiko_git_* variables

tobiko_dir: "{{ test_deploy_home }}/{{ tobiko_project }}"
tobiko_project:
  "{{ tobiko_git_repo | urlsplit('path') | regex_replace('^\\/|\\/$', '') | splitext | first }}"
tobiko_git_repo: '{{ git_base }}/x/tobiko.git'
tobiko_git_refspec: ''
tobiko_git_remote: 'origin'
tobiko_git_version: 'master'
tobiko_src_dir: ''


# --- Test configuration options ----------------------------------------------

# Configuration options
test_conf_file: '{{ test_dir | realpath }}/tobiko.conf'

test_conf: {}

# --- Test report options -----------------------------------------------------

# Remote directory where test cases shoulw write report files to
test_report_dir: "{{ test_dir | realpath }}"
test_report_files:
  - '{{ test_conf_file | realpath }}'
  - '{{ test_log_file | realpath }}'

# Test report files prefix
test_report_name: test_results

# Log file where test cases should write logging messages to
test_log_file: '{{ test_report_dir | realpath }}/tobiko.log'

# Local where test cases results are being collected to
test_collect_dir: '{{ test_src_dir | realpath }}/{{ test_report_name }}'
