---

# --- Tobiko workflow stages

test_stage: all


# --- Test deploy options -----------------------------------------------------

test_home: '{{ (ansible_user_dir + "/src") | realpath }}'
test_dir: '{{ tobiko_dir | realpath }}'
test_src_dir: ''
test_git_repo: ''
test_git_refspec: ''
test_git_version: ''


# --- Tobiko deploy options ---------------------------------------------------

tobiko_dir: '{{ test_home | realpath }}/tobiko'
tobiko_src_dir: '{{ role_path | realpath | dirname | dirname }}'
tobiko_git_repo: 'https://opendev.org/x/tobiko.git'
tobiko_git_refspec: ''
tobiko_git_version: ''


# --- Test configuration options ----------------------------------------------

# Configuration options
test_conf_file: '{{ test_dir | realpath }}/tobiko.conf'

test_conf: {}

# Logging options
test_log_debug: true

# --- Test report options -----------------------------------------------------

# Remote directory where test cases shoulw write report files to
test_report_dir: "{{ test_dir | realpath }}"
test_report_files:
  - '{{ test_conf_file | realpath }}'
  - '{{ test_log_file | realpath }}'

# Test report files prefix
test_report_name: test_results

# Log file where test cases should write logging messages to
test_log_file: '{{ test_report_dir | realpath }}/tobiko.log'

# Local where test cases results are being collected to
test_collect_dir: '{{ test_src_dir | realpath }}/{{ test_report_name }}'
