---

- name: "Check {{ tobiko_dir }} directory exists"
  stat:
    path: "{{ tobiko_dir | realpath }}"
  register: tobiko_dir_stat


- name: "Copy tobiko source code to node: {{ tobiko_source_dir }}/* -> {{ tobiko_dir }}"
  synchronize:
    src: "{{ tobiko_source_dir | realpath }}/."
    dest: "{{ tobiko_dir | realpath }}"
    use_ssh_args: true
    recursive: true
  when: "not tobiko_dir_stat.stat.exists"
